fragment ImageBlock on imageblock_Entry {
          __typename
          id
          typeHandle

           toggle
           toggle2

          image {
            url
            focalPoint
            alt
            width
            height
          }

          imageSlider {
            __typename

            ... on image_Entry {
              id
              title
              typeHandle
              body
              body2
              linkHandle {
                    label
                    url
               }
               linkHandle2 {
                    label
                    url
                }
              image {
                url
                focalPoint
                alt
                width
                height
              }
            }
          }
        }