import type { Metadata } from "next";
import { Montserrat, Geist } from "next/font/google";
import "./globals.css";
import ApolloAppProvider from "@/src/components/apollo-provider";
import TopNavClient from "./components/navigation/TopNavClient";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const montserrat = Montserrat({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body
        className={montserrat.className}
      >
        <ApolloAppProvider><TopNavClient />{children}</ApolloAppProvider>
      </body>
    </html>
  );
}
