# import ../fragments/ImageBlock.gql
# import ../fragments/heroBlock.gql

query GetHome($slug: [String]) {
  entry(section: "home", slug: $slug) {
    id
    title
    
    ... on homeentry_Entry {
      body

      pagebuilder {
        ...heroBlock
        ...ImageBlock
      }
    }
  }
}