query GetNav {
  entries(section: "topNav", level: 1) {
    id
    title

    ... on linkitem_Entry {
      linkHandle {
        title
        label
        url
      }
    }

    children {
      id
      title

      ... on linkitem_Entry {
        image {
            url
            focalPoint
            alt
            width
          id
          title
            height
          }
        linkHandle {
          title
          url
        }
      }

      children {
        id
        title

        ... on linkitem_Entry {
          linkHandle {
            title
            url
          }
        }
        
        children {
        id
        title

        ... on linkitem_Entry {
          linkHandle {
            title
            url
          }
        }
      }
      }
    }
  }
}