# import ../fragments/ImageBlock.gql
# import ../fragments/heroBlock.gql

query GetPage($uri: [String]) {
  entry(section: "pages", uri: $uri) {
    id
    title
    uri
    ... on pagesEntry_Entry {
      body
      pagebuilder {
        ...heroBlock
        ...ImageBlock
        
      }
    }
  }
}